### ISSUE TITLE
Crash in the air dimension

### ISSUE THREAD

**Issue by toddythebody** [McJty/ElementalDimensions#10]
Sorry I took so long to get this to you.

https://pastebin.com/aJHRQux5

**Comment by McJty** [comment]
np. I will check it out

**Comment by Serifina** [comment]
I've got it happening on my server as well. 

https://pastebin.com/yvgCw77H

**Comment by demfels** [comment]
Some issue on my server.
` [Error] Encountered an unexpected exceptionjava.util.ConcurrentModificationException	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_102]	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_102]	at bitmovers.elementaldimensions.dimensions.DimensionEvents.handleAir(DimensionEvents.java:61) ~[DimensionEvents.class:?]	at bitmovers.elementaldimensions.dimensions.DimensionEvents.onWorldTick(DimensionEvents.java:43) ~[DimensionEvents.class:?]	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_681_DimensionEvents_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269) ~[FMLCommonHandler.class:?]	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718) ~[MinecraftServer.class:?]	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]`

**Comment by demfels** [comment]
The amount of time I can be in the plane of air before the server crashes vary between seconds to 30-40 minutes.  I have a suspicion it has something to do with the ghasts.

The issue is pretty major, since it takes the entire server down, not just the client.

**Comment by demfels** [comment]
Here is my pastebin: https://pastebin.com/vHbyGfRb
