### ISSUE TITLE
Cannot open portal via right-click

### ISSUE THREAD

**Issue by SanAndreaP** [McJty/ElementalDimensions#6]
Minecraft 1.10.2
Minecraft Forge 12.18.3.2254
Elemental Dimensions 0.1.1

So as other users have described here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2723430-elemental-dimensions-work-in-progress-mod?comment=5

I simply cannot place a rune on the portal dialer, thus I can't open the portal. None of the runes work, my caracter does the hand motion but nothing happens, making this mod unplayable.

What caught my eye in my logs is this stack trace every time I try to right click:
```
[21:33:58] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.item.ItemTossEvent@525c0438:
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:419) ~[adz.class:?]
	at jds.bibliocraft.events.EventItemToss.DroppedItemEvent(EventItemToss.java:25) ~[EventItemToss.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_325_EventItemToss_DroppedItemEvent_ItemTossEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:603) [ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71019_a(EntityPlayer.java:729) [zs.class:?]
	at bitmovers.elementaldimensions.blocks.portal.PortalDialerTileEntity.dropDest(PortalDialerTileEntity.java:185) [PortalDialerTileEntity.class:?]
	at bitmovers.elementaldimensions.blocks.portal.PortalDialerTileEntity.onActivated(PortalDialerTileEntity.java:170) [PortalDialerTileEntity.class:?]
	at bitmovers.elementaldimensions.blocks.portal.PortalDialerBlock.onBlockActivatedC(PortalDialerBlock.java:128) [PortalDialerBlock.class:?]
	at elec332.abstraction.impl.MCAbstractedBlock.func_180639_a(MCAbstractedBlock.java:43) [MCAbstractedBlock.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) [lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) [me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

I suspect some kind of incompatibility / error with Bibliocraft, but I don't know if it's really an error solely in Bibliocraft or if there's some kind of mess up in Elemental Dimensions.

Here's the full log: https://gist.github.com/SanAndreasP/2072b2dbca634dd2eb73a6804dc04371

**Comment by McJty** [comment]
Those are two independent errors. I will check them out

**Comment by McJty** [comment]
@Elec332  seems that on 1.10.2 your onBlockActivatedC isn't called

**Comment by McJty** [comment]
Or hmm. They might actually be related

**Comment by McJty** [comment]
Ok fixed next release

**Comment by SanAndreaP** [comment]
Alright, I tried it and it works now, thanks.
